version = "1.0"

[metadata]
author_name = "Suraj Singh Khurana"
author_email = "2907suraj@gmail.com"
difficulty_explanation = "..."
category = "..."
tags = ["..."]

[verifier]
timeout_sec = 120.0

[agent]
timeout_sec = 900.0

[environment]
build_timeout_sec = 600.0